paths:
    graph_data_file_df: path/to/graph_files.csv
    targets_data_file: path/to/targets.pkl
    output_path: outputs
names:
    trainer_name: "gradnorm_trainer"
    task_name: "regression_training_task"
    model_name: "defectgnn"
    data_container_name: "data_container"
    data_provider_name: "data_provider"
data:
    graph_mode: "vacancy_aware"
    atom_feature_scheme: "specie_onehot"
    random_seed: 20250618
    shuffle: true
    train: "0.8"
    validation: "0.1"
    test: "0.1"
    cutoff: 4
    task_type: "regression"
    use_sigmoid: false
    target_types: ["atom"] # ["atom", "path"]
    target_col: "targets"
    target_name: "defectgnn_vacancy_aware_atom"
    num_targets: 1
    normalize_labels: true
    use_batch_norm: false
model:
    readout_mode: "standard"
    use_vacancy_features: true
    num_layers: 3
    input_size: 6
    atom_embedding_size: 32
    bond_embedding_size: 32
    hidden_size: 32
    rbf: "Bessel"
    sbf: "Spherical"
    num_spherical: 7
    num_radial: 6
    num_gaussian: 50
    gaussian_radial_var: 0.2
    gaussian_angular_var: 0.2
    envelope_exponent: 5
    num_embedding_fc_layers: 2
    num_b2b_res_layers: 2
    num_readout_fc_layers: 3
    feature_add_or_concat: "add"
    embedding_dropout: 0.3
    output_dropout: 0.3
    kernel_initializer: "GlorotOrthogonal"
    integrate_gate_mechanism: null
training:
    batch_size: 8
    num_steps: 3000000
    early_stopping_epochs: 500
    ema_decay: 0.999
    max_grad_norm: 10.0
    learning_rate: 0.001
    l2_loss_decay: 0.000
    use_huber_loss: false
    huber_delta: 1.0
    warmup_steps: 3000
    decay_rate: 0.1
    decay_steps: 4000000
    weight_lr: 0.001
    alpha: 1.5
misc:
    debug: false
    debug_step: 100
    enable_id_swap: false
    save_all_models: false
    save_all_predictions: false
    ckpt_max_to_keep: 3
    ckpt_path: null
    comment: ''
